FROM httpd:alpine

COPY ./views /usr/local/apache2/htdocs/

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# COPY httpd-foreground /usr/local/bin/

# COPY httpd-foreground /usr/local/bin/

EXPOSE 7074
